# config/app.yml for rails-settings-cached
defaults: &defaults
  year: 2019
  semester: "Fall"
  professor: "Dr. Walker"


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
